services:
  db:
    image: postgres:latest
    container_name: blog
    restart: always
    volumes:
      - ${HOME}/tmp:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 2000
      POSTGRES_USER: smile
      POSTGRES_DB: blog
